name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Pixi Environment
        uses: prefix-dev/setup-pixi@v0.9.5
        with:
          pixi-version: v0.68.1
          cache: true
      - name: Verify Formatting with Ruff
        run: pixi run ruff format --check .

      - name: Analyze Code Quality with Ruff Lint
        run: pixi run ruff check .
